name: Publish

on:
  push:
    tags: ['*']

permissions:
  contents: write

jobs:
  build-artifacts:
    name: Publish artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zig Setup
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: "0.12.0-dev.2541+894493549"

      - name: Zig Test
        run: zig build test

      - name: Zig Dylib
        run: zig build dylib -Doptimize=ReleaseSafe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            zig-out/include/*.h
            zig-out/lib/*.so
